### ISSUE TITLE
Change the behavior when abuseipdb can't be reached

### ISSUE THREAD

**Issue by matsmcp** [monsoft/abichecker#2]
As it is today, a communication error with abuseipdb will lead to mail being rejected.
I do not think this is the best setting.

For example, Scheduled maintenance at abuseipdb will cause mails being refused at my server.
I think that the correct way to handle this is to return dunno instead since we do not know in this case

**Comment by monsoft** [comment]
Ah, yes. I've had it running like this at home for months, I just forgot to push this change in behaviour to the Github repository.
Too busy :-( 
Thank you for reminding me :)
